name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Binary
      #     path: |
      #       ${{ steps.compile.outputs.BUILT_ARCHIVE }}
      #       ${{ steps.compile.outputs.BUILT_CHECKSUM }}
